#!/bin/bash

# Robust DP_GP_cluster execution script with logging and notifications
# Usage: ./run_dp_gp_monitored.sh

set -euo pipefail

# Configuration
INPUT_FILE="tissue_all/merged.txt"
OUTPUT_PREFIX="tissue_all/tissue_all"
PLOT_FORMAT="png"
ITERATIONS=2000
LOG_DIR="logs"

# Conda environment setup (modify these paths as needed)
CONDA_BASE="${HOME}/miniforge3"  # Using miniforge3
CONDA_ENV="DP_GP-env"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
LOG_FILE="${LOG_DIR}/dp_gp_${TIMESTAMP}.log"
PID_FILE="${LOG_DIR}/dp_gp.pid"

# Notification settings (configure these)
EMAIL="vschastlivaia@ibecbarcelona.eu"  # Set your email for notifications
SLACK_WEBHOOK=""  # Optional: Set Slack webhook URL
GITHUB_TOKEN="YOUR_GITHUB_TOKEN_HERE"  # Set your GitHub token for issue creation
GITHUB_REPO="vschastlivaia/DP_GP_cluster_private"  # GitHub repository

# Create logs directory
mkdir -p "${LOG_DIR}"

# Function to send notifications
send_notification() {
    local status="$1"
    local message="$2"
    local timestamp=$(date "+%Y-%m-%d %H:%M:%S")
    
    echo "[$timestamp] NOTIFICATION: $status - $message" | tee -a "${LOG_FILE}"
    
    # Email notification (if configured)
    if [[ -n "${EMAIL}" ]]; then
        {
            echo "Subject: DP_GP_cluster $status"
            echo ""
            echo "Timestamp: $timestamp"
            echo "Status: $status"
            echo "Message: $message"
            echo ""
            echo "Log file: $LOG_FILE"
            echo "Working directory: $(pwd)"
            echo "Host: $(hostname)"
        } | sendmail "${EMAIL}" 2>/dev/null || echo "Failed to send email notification"
    fi
    
    # Slack notification (if configured)
    if [[ -n "${SLACK_WEBHOOK}" ]]; then
        curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"🧬 DP_GP_cluster $status\\n*Host:* $(hostname)\\n*Time:* $timestamp\\n*Message:* $message\"}" \
            "${SLACK_WEBHOOK}" 2>/dev/null || echo "Failed to send Slack notification"
    fi
    
    # GitHub issue notification (if configured)
    if [[ -n "${GITHUB_TOKEN}" && -n "${GITHUB_REPO}" ]]; then
        local issue_title="DP_GP_cluster $status - $timestamp"
        local issue_body="**Status:** $status
**Timestamp:** $timestamp  
**Host:** $(hostname)
**Message:** $message
**Log file:** $LOG_FILE
**Working directory:** $(pwd)

---
*Auto-generated by DP_GP_cluster monitoring system*"
        
        curl -X POST \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${GITHUB_REPO}/issues" \
            -d "{
                \"title\": \"$issue_title\",
                \"body\": \"$issue_body\",
                \"labels\": [\"monitoring\", \"$(echo $status | tr '[:upper:]' '[:lower:]')\"]
            }" 2>/dev/null || echo "Failed to create GitHub issue notification"
    fi
}

# Function to cleanup on exit
cleanup() {
    local exit_code=$?
    
    if [[ -f "${PID_FILE}" ]]; then
        rm -f "${PID_FILE}"
    fi
    
    if [[ $exit_code -eq 0 ]]; then
        send_notification "COMPLETED" "DP_GP_cluster finished successfully"
    else
        send_notification "FAILED" "DP_GP_cluster exited with code $exit_code"
    fi
    
    echo "[$timestamp] Process cleanup completed" >> "${LOG_FILE}"
}

# Function to handle signals
handle_signal() {
    local signal=$1
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Received signal: $signal" >> "${LOG_FILE}"
    send_notification "INTERRUPTED" "Process interrupted by signal $signal"
    exit 1
}

# Set up signal handlers
trap 'handle_signal SIGTERM' TERM
trap 'handle_signal SIGINT' INT
trap 'handle_signal SIGHUP' HUP
trap 'cleanup' EXIT

# Log system information
{
    echo "======================================"
    echo "DP_GP_cluster Execution Started"
    echo "======================================"
    echo "Timestamp: $(date '+%Y-%m-%d %H:%M:%S')"
    echo "Host: $(hostname)"
    echo "User: $(whoami)"
    echo "Working Directory: $(pwd)"
    echo "Python Version: $(python --version 2>&1 || echo 'Python not found')"
    echo "Memory Info:"
    free -h || echo "free command not available"
    echo "Disk Space:"
    df -h . || echo "df command not available"
    echo "Input file size: $(ls -lh ${INPUT_FILE} | awk '{print $5}' || echo 'File not found')"
    echo "Command: DP_GP_cluster.py -i ${INPUT_FILE} -o ${OUTPUT_PREFIX} -p ${PLOT_FORMAT} -n ${ITERATIONS} --plot"
    echo "======================================"
} >> "${LOG_FILE}"

# Initialize conda environment
initialize_conda() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Initializing conda environment..." >> "${LOG_FILE}"
    
    # Try to source conda
    if [[ -f "${CONDA_BASE}/etc/profile.d/conda.sh" ]]; then
        source "${CONDA_BASE}/etc/profile.d/conda.sh"
        echo "Conda initialized from ${CONDA_BASE}" >> "${LOG_FILE}"
    elif [[ -f "${HOME}/miniforge3/etc/profile.d/conda.sh" ]]; then
        source "${HOME}/miniforge3/etc/profile.d/conda.sh"
        echo "Conda initialized from ${HOME}/miniforge3" >> "${LOG_FILE}"
    elif [[ -f "${HOME}/miniconda3/etc/profile.d/conda.sh" ]]; then
        source "${HOME}/miniconda3/etc/profile.d/conda.sh"
        echo "Conda initialized from ${HOME}/miniconda3" >> "${LOG_FILE}"
    else
        echo "Warning: conda.sh not found, trying direct activation" >> "${LOG_FILE}"
    fi
    
    # Activate environment
    if conda activate "${CONDA_ENV}" 2>> "${LOG_FILE}"; then
        echo "Successfully activated conda environment: ${CONDA_ENV}" >> "${LOG_FILE}"
    else
        echo "Failed to activate conda environment: ${CONDA_ENV}" >> "${LOG_FILE}"
        send_notification "ERROR" "Failed to activate conda environment: ${CONDA_ENV}"
        exit 1
    fi
}

# Check prerequisites
if [[ ! -f "${INPUT_FILE}" ]]; then
    send_notification "ERROR" "Input file ${INPUT_FILE} not found"
    exit 1
fi

# Initialize conda environment
initialize_conda

# Check if DP_GP_cluster.py is available after conda activation
if ! command -v DP_GP_cluster.py &> /dev/null; then
    send_notification "ERROR" "DP_GP_cluster.py command not found after conda activation"
    exit 1
fi

# Store PID for monitoring
echo $$ > "${PID_FILE}"

# Send start notification
send_notification "STARTED" "DP_GP_cluster execution started with PID $$"

# Execute the main command with full logging
{
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting DP_GP_cluster execution..."
    
    # Use timeout to prevent infinite hangs (we need at least 78 hours)
    #timeout 300000 
    DP_GP_cluster.py \
        -i "${INPUT_FILE}" \
        -o "${OUTPUT_PREFIX}" \
        -p "${PLOT_FORMAT}" \
        -n "${ITERATIONS}" \
        --plot 2>&1
    
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] DP_GP_cluster completed successfully"
    
} | tee -a "${LOG_FILE}"

# Log final status
{
    echo "======================================"
    echo "Execution Summary"
    echo "======================================"
    echo "End time: $(date '+%Y-%m-%d %H:%M:%S')"
    echo "Output files created:"
    ls -la "${OUTPUT_PREFIX}"* 2>/dev/null || echo "No output files found"
    echo "======================================"
} >> "${LOG_FILE}"